config/routes.rb
require 'sidekiq/web'
Betterlaundry::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :rooms do
        put :sync
      end
      resources :machines do
        put :notify
      end
    end
  end

  mount Sidekiq::Web => '/sidekiq'

  get '*foo', :to => 'ember#start'
  root to: "ember#start"
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  belongs_to :room
  default_scope ->{ order(:number) }
  scope :available, ->{ where(remaining: nil, out_of_service: false)}
  scope :washers, ->{ where(kind: "washer")}
  scope :driers, ->{ where(kind: "dryer")}

  def available?
    remaining == nil
  end

  def done?
    remaining == 0
  end

  def busy?
    remaining != nil
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  validates :lvid, uniqueness: true
  validates :name, uniqueness: true
  has_many :machines

  def utilization
    return 100 unless machines.count > 0
    in_use = machines.where("remaining IS NOT NULL").count
    return (in_use.to_f/machines.count*100).to_i
  end

  def washers
    machines.washers
  end

  def dryers
    machines.driers
  end
end

app/controllers/api/v1/machines_controller.rb
class Api::V1::MachinesController < ApplicationController
  respond_to :json

  def index
    respond_with Machine.all
  end

  def show
    respond_with Machine.find(params[:id])
  end

  def notify(user)
    NotificationWorker.perform_async(params[:machine_id], user.email)
    respond_with true
  end
end

app/controllers/api/v1/rooms_controller.rb
class Api::V1::RoomsController < ApplicationController
  respond_to :json

  def index
    respond_with Room.all
  end

  def show
    respond_with Room.find(params[:id])
  end

  def sync
    RoomSyncWorker.perform_async(params[:room_id])
    respond_with true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ember_controller.rb
class EmberController < ApplicationController
  def start
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = RoomDecorator.decorate_collection(Room.all)
  end

  def show
    @room = RoomDecorator.decorate(Room.find(params[:id]))
  end

  def sync
    RoomSyncJob.perform_later params[:room_id]
    flash[:notice] = "Syncing the room"
    redirect_to request.referrer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
      div class="alert alert-#{name == :notice ? "success" : "error"}"
         a.close data-dismiss="alert"
          | × 
         = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title BetterLaundry
    = csrf_meta_tags

    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"

  body
    nav class="navbar navbar-inverse navbar-fixed-top"
      div class="container"
        div class="navbar-header"
          button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
            span class="sr-only" Toggle navigation
            span class="icon-bar"
            span class="icon-bar"
            span class="icon-bar"
          = link_to "BetterLaundry", root_path, class: "navbar-brand"
        div id="navbar" class="collapse navbar-collapse"
          ul class="nav navbar-nav"

    .container-fluid
      .content
          = render partial: "layouts/messages"
          = yield

    footer
      p
        ' &copy; #{Date.today.year}
        = link_to "Atlanta Coding Company, LLC", "http://atlcoding.co"

app/views/machines/_machine.html.slim
.col-lg-3.col-md-4.col-sm-6.col-xs-12
  .panel.panel-default
    .panel-heading
      h3 class="panel-title"
        = machine.kind.capitalize
        |  #
        = machine.number
    .panel-body
      .progress
        div class=machine.progress_bar_class role="progressbar" aria-valuenow="#{machine.percent}" aria-valuemin="0" aria-valuemax="100" style="width: #{machine.percent}%;"
          span.sr-only #{machine.percent}% Complete
      - if machine.available?
        p Available!
      - elsif machine.out_of_service?
        p Out of Service
      - elsif machine.remaining > 0
        p
          = machine.remaining
          |  minutes remaining
      - else
        p Waiting for Unload

app/views/rooms/index.html.slim
br
- @rooms.each do |room|
  .col-lg-3.col-md-4.col-sm-6.col-xs-12
    a href="#{room_path(room)}"
      .panel.panel-default
        .panel-heading
          h3.panel-title=room.name
        .panel-body
          = image_tag "washer.png", width: 32
          | &nbsp;
          = room.washers.available.count
          | /
          = room.washers.count
          | &nbsp;
          = image_tag "dryer.png", width: 32
          | &nbsp;
          = room.dryers.available.count
          | /
          = room.dryers.count

app/views/rooms/show.html.slim
.row
  .col-md-4
    h1=@room.name
  .col-md-2.pull-right
    small
      - if @room.last_synced
        ' Updated
        =time_ago_in_words(@room.last_synced)
        |  ago
      - else
        | Never updated
.row
  .col-md-1.col-xs-2
      = image_tag "washer.png", class: "img-responsive", width: 32
      - if @room.washers.available.count > 0
        .label.label-default
          = @room.washers.available.count
          |  open
      - else
        .label.label-danger Full
  .col-md-1.col-xs-2
      = image_tag "dryer.png", class: "img-responsive", width: 32
      - if @room.dryers.available.count > 0
        .label.label-default
          = @room.dryers.available.count
          |  open
      - else
        .label.label-danger Full
br
-@room.machines.each do |machine|
  = render machine